export const specialtiesData = [
'APARATE RADIOELECTRICE DE UZ CASNIC', 
'CALCULATOARE', 
'ELECTRONICĂ', 
'MAŞINI, INSTALAŢII FRIGORIFICE ŞI SISTEME DE CLIMATIZARE', 
'TELERADIO COMUNICAŢII',
'ELECTROENERGETICĂ si ELECTROMECANICĂ',
'METROLOGIA ȘI CERTIFICAREA CONFORMITĂȚII',
'TELECOMUNICAȚII',
'REȚELE DE CALCULATOARE',
'AUTOMATICA',
'COMUNICATII POSTALE'
]
